version: "2"
run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - importas
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - gocyclo
    - revive
    - gosec
    - misspell
    - nakedret
    - unconvert
    - whitespace
    - rowserrcheck
    - goconst
    - asciicheck
    - nestif
    - sqlclosecheck
  settings:
    govet:
      disable:
        - shadow
  exclusions:
    rules:
      - linters:
          - revive
        text: "exported:.*"
      - linters:
          - revive
        text: "package-comments:.*"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: order