{
 "title": "Inventoryservice Overview",
 "tags": [ "inventory" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_goroutines, job)"
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(service_requests_total_bucket{job=~\"$job\"}[$__rate_interval])) by (le, job))",
     "legendFormat": "p95/{{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(service_requests_total_bucket{job=~\"$job\"}[$__rate_interval])) by (le, job))",
     "legendFormat": "p99/{{job}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(service_requests_total_count{job=~\"$job\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(irate(service_requests_total_count{code=\"Internal\", job=~\"$job\"}[$__rate_interval])) / sum(irate(service_requests_total_count{job=~\"$job\"}[$__rate_interval]))) or on() vector(0)",
     "legendFormat": "Rate"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}